version: '3'
services:
  frontend-spa:
    image: nginx:latest
    container_name: frontend-app
    ports:
      - 80:80
    volumes: 
      - ./nginx/frontend:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d 
    networks:
      - minha-rede
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    depends_on:
      keyclocak-server:  
        condition: service_started
        
  mysql-server:
    image: mysql:8.0.22
    container_name: mysql-server-db
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306' 
    expose:
      - 3306
    volumes:
      - volume-mysql-keycloak:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ,"-u", "$$MYSQL_USER","--password=$$MYSQL_PASSWORD"]
      timeout: 20s
      interval: 2s
      retries: 10    
    networks:
      - minha-rede
      
  quarkus-rest:
    container_name: quarkus-rest-app
    build:
      context: quarkus-rest-app
      dockerfile: Dockerfile.jvm
    networks:
      - minha-rede 
    ports:
      - '8080:8080' 
    volumes:
      - $HOME/.m2:/root/.m2  
    environment:
      QUARKUS_PROFILE: localDocker
      KEYCLOAK_URL: http://gateway.docker.internal/realms/meetup
      KEYCLOAK_CLIENT_ID: backend-app
      KEYCLOAK_CLIENT_SECRET: lVFlfBUJu3Ii5ndBmLH5u2aKJEfhnqKj
      LIST_ORIGINS_HOSTS_CORS: 'http://gateway.docker.internal,http://localhost'
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    depends_on:
      keyclocak-server:  
        condition: service_started
        
  keyclocak-server:
    image: quay.io/keycloak/keycloak:19.0
    container_name: keycloak-server-app 
    volumes:
      - ./imports_reamls:/opt/keycloak/data/import
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      TZ: UTC
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: token-exchange
      KC_HTTP_ENABLED: 'true'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB: mysql
      KC_DB_URL: 'jdbc:mysql://mysql-server/keycloak'
      # KEYCLOAK_IMPORT: /tmp/import/global.json
    entrypoint: /opt/keycloak/bin/kc.sh start --auto-build --import-realm
    ports:
      - 8180:8080   
    expose:
      - 8080
    networks:
      - minha-rede
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      timeout: 20s
      interval: 2s
      retries: 10      
    depends_on:
      mysql-server:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"        
volumes:
  volume-mysql-keycloak:
    name: volume-mysql-keycloak
    
networks:
  minha-rede:
    name: rede-externa    
    
  
